version: "3.4"
services:
  sonar-qube:
    image: sonarqube:7.9.2-community
    container_name: 'sonar-qube'
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://dc-postgres:5432/sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./data/sonarqube/conf:/opt/sonarqube/conf
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/lib:/opt/sonarqube/lib/bundled-plugins
  postgres:
    image: postgres:12.1
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/postgres:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data/postgres/data:/var/lib/postgresql/data

