version: "3.4"
services:
  cassandra:
    image: "cassandra:3.11.9"
    container_name: 'infra-cassandra'
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    network_mode: "host"